package org.craneprint.craneserver.ui;

import java.util.ArrayList;
import java.util.Iterator;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.LoginForm;
import com.vaadin.ui.LoginForm.LoginEvent;
import com.vaadin.ui.LoginForm.LoginListener;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class LoginView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private LoginForm loginForm;
	private static final long serialVersionUID = 3104951577756274132L;
	private Panel loginPanel;
	
	private ArrayList<LoginEventListener> loginListeners = new ArrayList<LoginEventListener>();

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public LoginView(LoginEventListener ll) {
		addLoginListener(ll);
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	protected void addLoginListener(LoginEventListener listener) {
		loginListeners.add(listener);
	}

	protected void removeLoginListener(LoginEventListener listener) {
		loginListeners.remove(listener);
	}

	private void fireLoginEvent(LoginEvent loginEvent) {
		// loop through each listener and pass on the event if needed
		Iterator i = loginListeners.iterator();
		while(i.hasNext()) {
			LoginEventListener ll = (LoginEventListener)i.next();
			ll.handleLoginEvent(loginEvent);
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// loginPanel
		loginPanel = buildLoginPanel();
		mainLayout.addComponent(loginPanel);
		mainLayout.setComponentAlignment(loginPanel, Alignment.MIDDLE_CENTER);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildLoginPanel() {
		// common part: create layout
		loginPanel = new Panel();
		loginPanel.setImmediate(false);
		loginPanel.setWidth("-1px");
		loginPanel.setHeight("-1px");
		
		// loginForm
		loginForm = new LoginForm();
		loginForm.setStyleName("v-loginform");
		loginForm.setImmediate(false);
		loginForm.setWidth("185px");
		loginForm.setHeight("162px");
		loginForm.addLoginListener(new LoginListener() {
			@Override
			public void onLogin(LoginEvent event) {
				fireLoginEvent(event);
			}
		});
		loginPanel.setContent(loginForm);
		
		return loginPanel;
	}

}
