package org.craneprint.craneserver.ui;

import java.util.ArrayList;
import java.util.Iterator;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.LoginForm;
import com.vaadin.ui.LoginForm.LoginEvent;
import com.vaadin.ui.LoginForm.LoginListener;
import com.vaadin.ui.VerticalLayout;

public class LoginView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private LoginForm loginForm;
	
	private ArrayList<LoginEventListener> loginListeners = new ArrayList<LoginEventListener>();

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public LoginView(LoginEventListener ll) {
		addLoginListener(ll);
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// loginForm
		loginForm = new LoginForm();
		loginForm.setStyleName("v-loginform");
		loginForm.setImmediate(false);
		loginForm.setWidth("-1px");
		loginForm.setHeight("-1px");
		loginForm.addLoginListener(new LoginListener(){
			public void onLogin(LoginEvent le){
				fireLogin(le);
			}
		});
		mainLayout.addComponent(loginForm);

		mainLayout.setComponentAlignment(loginForm, Alignment.MIDDLE_CENTER);

		return mainLayout;
	}

	protected void addLoginListener(LoginEventListener listener) {
		loginListeners.add(listener);
	}

	protected void removeLoginListener(LoginEventListener listener) {
		loginListeners.remove(listener);
	}

	protected void fireLogin(LoginEvent loginEvent) {
		// loop through each listener and pass on the event if needed
		Iterator i = loginListeners.iterator();
		while(i.hasNext()) {
			LoginEventListener ll = (LoginEventListener)i.next();
			ll.handleLoginEvent(loginEvent);
		}
	}

}
