package org.craneprint.craneserver.ui;

import java.awt.Panel;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.CustomLayout;
import com.vaadin.ui.VerticalLayout;

public class SlicingTab extends CustomComponent {

	@AutoGenerated
	private CustomLayout mainLayout;
	private Craneprint_craneserverUI ui;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SlicingTab(Craneprint_craneserverUI u) {
		ui = u;
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		//mainLayout = new VerticalLayout();
		//mainLayout = new CustomLayout("pre_parsed_json_inline");
        // wrap custom layout inside a panel
        //final Panel customLayoutPanel = new Panel("Panel containing custom layout (mainLayout.html)");
        //customLayoutPanel.addComponent(mainLayout);
	}

}
